# Generated by Django 5.2.7 on 2026-03-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub_app', '0005_remove_booking_platform_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='problem_photo',
            field=models.ImageField(blank=True, null=True, upload_to='problem_photos/'),
        ),
    ]
