# Generated by Django 5.2.7 on 2026-03-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub_app', '0006_booking_problem_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
